name: Build binaries

on:
  schedule:
    - cron: "0 3 */2 * *"
  push:
  pull_request:
    paths:
    - '.github/workflows/*.yml'
    - './scripts/*.sh'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Checkout builder
        uses: actions/checkout@v1

      - name: Install arm toolchain
        run: ./scripts/install_arm.sh

      - name: Checkout ulab/micropython
        run: ./scripts/init.sh

      - name: Create artifacts directory
        run: mkdir ./artifacts

      # this section is only for test purposes
      # - name: Compile unix port
      #   if: always()
      #   run: ./scripts/unix.sh

      - name: Compile for PYBD_SF6
        if: always()
        run: ./scripts/stm32/pybd_sf6.sh

      - name: Compile for pybv10 board
        if: always()
        run: ./scripts/stm32/pybv10.sh

      - name: Compile for pybv11 board
        if: always()
        run: ./scripts/stm32/pybv11.sh

      - name: Compile for raspberry py nano
        if: always()
        run: ./scripts/rp2/arduino_nano_connect.sh

      - name: Compile for raspberry py pico
        if: always()
        run: ./scripts/rp2/pico.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          title: "Release date ${{ steps.date.outputs.date }}"
          files: ./artifacts/*
